[package]
name = "fs-more-test-harness"
version = "0.8.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
fs-more = { path = "../.." }
fs-more-test-harness-tree-schema = { path = "../test-harness-tree-schema" }

dunce = { version = "1.0.5" }
rand = "0.10.2"
rand_chacha = "0.10.0"
thiserror = "2.0.20"
tempfile = "3.27.0"
humansize = "2.1.3"
assert_matches = "1.5.0"
