[package]
name = "fs-more"
version = "0.2.2"
rust-version = "1.63.0"
authors = [
    "Simon Goričar <simon.peter.goricar@gmail.com>"
]
edition = "2021"
description = "Convenient file and directory operations with progress reporting built on top of std::fs."
readme = "README.md"
keywords = [
    "fs",
    "copy",
    "move",
    "progress"
]
categories = [
    "filesystem"
]
license = "MIT"
repository = "https://github.com/simongoricar/fs-more"
include = [
    "/src",
    "/test-harness",
    "/test-harness-macros",
    "/tests"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "test-harness",
    "test-harness-macros"
]

[features]
fs-err = ["dep:fs-err"]


[dependencies]
dunce = "1.0.4"
fs-err = { version = "2.9.0", optional = true }
path-clean = "1.0.1"
thiserror = "1.0.48"

[dev-dependencies]
assert_fs = "1.0.13"
assert_matches = "1.5.0"
fs-more-test-harness = { path = "./test-harness" }
