name: Build and test Rust code

on:
  push:
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always
  # See https://rustmagazine.org/issue-2/optimize-rust-comptime/#step-3:-disable-incremental-compilation
  CARGO_INCREMENTAL: 0

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Set up required tools
      run: sudo apt-get update && sudo apt-get install curl build-essential -y
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
    - name: Install stable Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run doc tests
      run: cargo test --workspace --doc --all-features --verbose
    - name: Run non-doc tests
      run: cargo test --workspace --all-targets --all-features --verbose
