name: Build and test Rust code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
    - name: Set up required tools
      run: sudo apt-get update && sudo apt-get install curl build-essential -y
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
    - name: Install stable Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
